// 种子数据：与原版 model/data.go、model/config.go、model/init.go、model/article.go 保持一致

export interface PermissionSeed {
  title: string;
  description: string;
  method: string;
  path: string;
}

export const PERMISSIONS_SEED: PermissionSeed[] = [
  { title: '创建广告', description: '新增广告内容', method: 'GRPC', path: '/api.v1.AdvertisementAPI/CreateAdvertisement' },
  { title: '删除广告', description: '删除指定广告', method: 'GRPC', path: '/api.v1.AdvertisementAPI/DeleteAdvertisement' },
  { title: '查看广告详情', description: '查看单个广告详情', method: 'GRPC', path: '/api.v1.AdvertisementAPI/GetAdvertisement' },
  { title: '查看广告列表', description: '查看广告列表', method: 'GRPC', path: '/api.v1.AdvertisementAPI/ListAdvertisement' },
  { title: '更新广告', description: '修改广告内容', method: 'GRPC', path: '/api.v1.AdvertisementAPI/UpdateAdvertisement' },
  { title: '批量审核文章', description: '批量审核文章状态', method: 'GRPC', path: '/api.v1.ArticleAPI/CheckArticles' },
  { title: '抓取网页文章', description: '根据链接抓取并解析文章标题与正文', method: 'GRPC', path: '/api.v1.ArticleAPI/CrawlArticle' },
  { title: '创建文章', description: '在后台新增文章或单页', method: 'GRPC', path: '/api.v1.ArticleAPI/CreateArticle' },
  { title: '删除文章', description: '删除指定文章', method: 'GRPC', path: '/api.v1.ArticleAPI/DeleteArticle' },
  { title: '删除回收站文章', description: '彻底删除回收站中的文章', method: 'GRPC', path: '/api.v1.ArticleAPI/DeleteRecycleArticle' },
  { title: '清空回收站文章', description: '清空回收站中的全部文章', method: 'GRPC', path: '/api.v1.ArticleAPI/EmptyRecycleArticle' },
  { title: '查看文章详情（全部状态）', description: '查看任意状态下的文章详情', method: 'GRPC', path: '/api.v1.ArticleAPI/GetArticle' },
  { title: '查看文章列表', description: '查看文章与单页列表', method: 'GRPC', path: '/api.v1.ArticleAPI/ListArticle' },
  { title: '查看回收站文章列表', description: '查看回收站中的文章列表', method: 'GRPC', path: '/api.v1.ArticleAPI/ListRecycleArticle' },
  { title: '设置文章推荐', description: '设置或取消文章推荐状态', method: 'GRPC', path: '/api.v1.ArticleAPI/RecommendArticles' },
  { title: '恢复回收站文章', description: '将文章从回收站恢复', method: 'GRPC', path: '/api.v1.ArticleAPI/RestoreRecycleArticle' },
  { title: '批量修改文章分类', description: '批量调整文章所属分类', method: 'GRPC', path: '/api.v1.ArticleAPI/SetArticlesCategory' },
  { title: '更新文章或单页', description: '修改文章或单页内容', method: 'GRPC', path: '/api.v1.ArticleAPI/UpdateArticle' },
  { title: '查看附件详情', description: '根据附件 ID 查看详情', method: 'GRPC', path: '/api.v1.AttachmentAPI/GetAttachment' },
  { title: '查看附件列表', description: '查看系统附件列表', method: 'GRPC', path: '/api.v1.AttachmentAPI/ListAttachment' },
  { title: '更新附件信息', description: '修改附件元数据', method: 'GRPC', path: '/api.v1.AttachmentAPI/UpdateAttachment' },
  { title: '创建轮播图', description: '新增轮播图配置', method: 'GRPC', path: '/api.v1.BannerAPI/CreateBanner' },
  { title: '删除轮播图', description: '删除指定轮播图', method: 'GRPC', path: '/api.v1.BannerAPI/DeleteBanner' },
  { title: '查看轮播图详情', description: '根据轮播图 ID 查看详情', method: 'GRPC', path: '/api.v1.BannerAPI/GetBanner' },
  { title: '查看轮播图列表', description: '查看轮播图列表', method: 'GRPC', path: '/api.v1.BannerAPI/ListBanner' },
  { title: '更新轮播图', description: '修改轮播图配置', method: 'GRPC', path: '/api.v1.BannerAPI/UpdateBanner' },
  { title: '创建文档分类', description: '新增文档分类', method: 'GRPC', path: '/api.v1.CategoryAPI/CreateCategory' },
  { title: '删除文档分类', description: '删除指定文档分类', method: 'GRPC', path: '/api.v1.CategoryAPI/DeleteCategory' },
  { title: '查看文档分类详情', description: '根据分类 ID 查看详情', method: 'GRPC', path: '/api.v1.CategoryAPI/GetCategory' },
  { title: '查看文档分类列表', description: '查看文档分类列表', method: 'GRPC', path: '/api.v1.CategoryAPI/ListCategory' },
  { title: '更新文档分类', description: '修改文档分类信息', method: 'GRPC', path: '/api.v1.CategoryAPI/UpdateCategory' },
  { title: '批量审核评论', description: '批量审核评论状态', method: 'GRPC', path: '/api.v1.CommentAPI/CheckComment' },
  { title: '删除评论', description: '删除指定评论', method: 'GRPC', path: '/api.v1.CommentAPI/DeleteComment' },
  { title: '查看评论详情', description: '查看单条评论详情', method: 'GRPC', path: '/api.v1.CommentAPI/GetComment' },
  { title: '查看评论列表', description: '查看评论列表', method: 'GRPC', path: '/api.v1.CommentAPI/ListComment' },
  { title: '更新评论', description: '修改评论内容或状态', method: 'GRPC', path: '/api.v1.CommentAPI/UpdateComment' },
  { title: '查看服务器硬件信息', description: '查看服务器硬件与资源信息', method: 'GRPC', path: '/api.v1.ConfigAPI/GetDeviceInfo' },
  { title: '查看环境依赖检测', description: '查看服务器环境依赖检测结果', method: 'GRPC', path: '/api.v1.ConfigAPI/GetEnvs' },
  { title: '查看系统统计信息', description: '查看系统运行统计信息', method: 'GRPC', path: '/api.v1.ConfigAPI/GetStats' },
  { title: '查看系统配置列表', description: '查看系统配置项列表', method: 'GRPC', path: '/api.v1.ConfigAPI/ListConfig' },
  { title: '更新系统配置', description: '修改系统配置项', method: 'GRPC', path: '/api.v1.ConfigAPI/UpdateConfig' },
  { title: '更新站点地图', description: '手动更新站点地图文件', method: 'GRPC', path: '/api.v1.ConfigAPI/UpdateSitemap' },
  { title: '审核文档', description: '审核文档发布状态', method: 'GRPC', path: '/api.v1.DocumentAPI/CheckDocument' },
  { title: '删除文档', description: '删除指定文档', method: 'GRPC', path: '/api.v1.DocumentAPI/DeleteDocument' },
  { title: '下载待审文档', description: '下载待审核文档文件', method: 'GRPC', path: '/api.v1.DocumentAPI/DownloadDocumentToBeReviewed' },
  { title: '查看文档详情', description: '根据文档 ID 查看详情', method: 'GRPC', path: '/api.v1.DocumentAPI/GetDocument' },
  { title: '查看文档列表', description: '查看文档列表', method: 'GRPC', path: '/api.v1.DocumentAPI/ListDocument' },
  { title: '设置文档推荐', description: '设置或取消文档推荐状态', method: 'GRPC', path: '/api.v1.DocumentAPI/SetDocumentRecommend' },
  { title: '一键重转失败文档', description: '重新转码全部失败文档', method: 'GRPC', path: '/api.v1.DocumentAPI/SetDocumentReconvert' },
  { title: '批量修改文档分类', description: '批量调整文档所属分类', method: 'GRPC', path: '/api.v1.DocumentAPI/SetDocumentsCategory' },
  { title: '批量设置文档语言', description: '批量设置文档语言', method: 'GRPC', path: '/api.v1.DocumentAPI/SetDocumentsLanguage' },
  { title: '更新文档', description: '修改文档内容或设置', method: 'GRPC', path: '/api.v1.DocumentAPI/UpdateDocument' },
  { title: '创建友链', description: '新增一条友链', method: 'GRPC', path: '/api.v1.FriendlinkAPI/CreateFriendlink' },
  { title: '删除友链', description: '删除指定友链', method: 'GRPC', path: '/api.v1.FriendlinkAPI/DeleteFriendlink' },
  { title: '查看友链详情', description: '根据友链 ID 查看详情', method: 'GRPC', path: '/api.v1.FriendlinkAPI/GetFriendlink' },
  { title: '查看友链列表', description: '查看站点友链列表', method: 'GRPC', path: '/api.v1.FriendlinkAPI/ListFriendlink' },
  { title: '更新友链', description: '修改友链信息', method: 'GRPC', path: '/api.v1.FriendlinkAPI/UpdateFriendlink' },
  { title: '创建用户组', description: '创建新的用户组', method: 'GRPC', path: '/api.v1.GroupAPI/CreateGroup' },
  { title: '删除用户组', description: '删除指定用户组', method: 'GRPC', path: '/api.v1.GroupAPI/DeleteGroup' },
  { title: '查看用户组权限', description: '查看用户组当前授权', method: 'GRPC', path: '/api.v1.GroupAPI/GetGroupPermission' },
  { title: '查看用户组列表', description: '查看系统中的用户组列表', method: 'GRPC', path: '/api.v1.GroupAPI/ListGroup' },
  { title: '更新用户组', description: '修改用户组信息', method: 'GRPC', path: '/api.v1.GroupAPI/UpdateGroup' },
  { title: '更新用户组权限', description: '为用户组分配或调整权限', method: 'GRPC', path: '/api.v1.GroupAPI/UpdateGroupPermission' },
  { title: '删除语言', description: '删除指定语言配置', method: 'GRPC', path: '/api.v1.LanguageAPI/DeleteLanguage' },
  { title: '查看语言列表', description: '查看系统语言配置列表', method: 'GRPC', path: '/api.v1.LanguageAPI/ListLanguage' },
  { title: '更新语言', description: '修改语言配置', method: 'GRPC', path: '/api.v1.LanguageAPI/UpdateLanguage' },
  { title: '更新语言状态', description: '启用或停用指定语言', method: 'GRPC', path: '/api.v1.LanguageAPI/UpdateLanguageStatus' },
  { title: '创建导航', description: '新增导航项', method: 'GRPC', path: '/api.v1.NavigationAPI/CreateNavigation' },
  { title: '删除导航', description: '删除指定导航项', method: 'GRPC', path: '/api.v1.NavigationAPI/DeleteNavigation' },
  { title: '查看导航列表', description: '查看导航列表', method: 'GRPC', path: '/api.v1.NavigationAPI/ListNavigation' },
  { title: '更新导航', description: '修改导航信息', method: 'GRPC', path: '/api.v1.NavigationAPI/UpdateNavigation' },
  { title: '关闭订单', description: '关闭待支付的订单', method: 'GRPC', path: '/api.v1.OrderAPI/CloseOrder' },
  { title: '删除订单', description: '删除指定订单', method: 'GRPC', path: '/api.v1.OrderAPI/DeleteOrder' },
  { title: '查看订单详情', description: '根据订单 ID 查看详情', method: 'GRPC', path: '/api.v1.OrderAPI/GetOrder' },
  { title: '查看订单列表', description: '查看系统订单列表', method: 'GRPC', path: '/api.v1.OrderAPI/ListOrder' },
  { title: '系统充值', description: '后台为用户充值或扣减积分', method: 'GRPC', path: '/api.v1.OrderAPI/SystemRecharge' },
  { title: '查看权限详情', description: '根据权限 ID 查看详情', method: 'GRPC', path: '/api.v1.PermissionAPI/GetPermission' },
  { title: '查看权限列表', description: '查看系统权限列表', method: 'GRPC', path: '/api.v1.PermissionAPI/ListPermission' },
  { title: '更新权限信息', description: '修改权限名称或说明', method: 'GRPC', path: '/api.v1.PermissionAPI/UpdatePermission' },
  { title: '取消用户处罚', description: '取消用户当前处罚', method: 'GRPC', path: '/api.v1.PunishmentAPI/CancelPunishment' },
  { title: '创建用户处罚', description: '新增用户处罚记录', method: 'GRPC', path: '/api.v1.PunishmentAPI/CreatePunishment' },
  { title: '查看处罚详情', description: '查看单条处罚记录详情', method: 'GRPC', path: '/api.v1.PunishmentAPI/GetPunishment' },
  { title: '查看用户处罚列表', description: '查看用户处罚记录列表', method: 'GRPC', path: '/api.v1.PunishmentAPI/ListPunishment' },
  { title: '更新用户处罚', description: '修改处罚规则或时效', method: 'GRPC', path: '/api.v1.PunishmentAPI/UpdatePunishment' },
  { title: '清空回收站文档', description: '清空回收站中的全部文档', method: 'GRPC', path: '/api.v1.RecycleAPI/ClearRecycleDocument' },
  { title: '删除回收站文档', description: '彻底删除回收站中的文档', method: 'GRPC', path: '/api.v1.RecycleAPI/DeleteRecycleDocument' },
  { title: '查看回收站文档列表', description: '查看回收站中的文档列表', method: 'GRPC', path: '/api.v1.RecycleAPI/ListRecycleDocument' },
  { title: '恢复回收站文档', description: '将文档从回收站恢复', method: 'GRPC', path: '/api.v1.RecycleAPI/RecoverRecycleDocument' },
  { title: '删除举报', description: '删除指定举报记录', method: 'GRPC', path: '/api.v1.ReportAPI/DeleteReport' },
  { title: '查看举报列表', description: '查看用户举报列表', method: 'GRPC', path: '/api.v1.ReportAPI/ListReport' },
  { title: '处理举报', description: '更新举报处理结果', method: 'GRPC', path: '/api.v1.ReportAPI/UpdateReport' },
  { title: '删除搜索记录', description: '删除指定搜索记录', method: 'GRPC', path: '/api.v1.SearchRecordAPI/DeleteSearchRecord' },
  { title: '查看搜索记录列表', description: '查看站内搜索记录列表', method: 'GRPC', path: '/api.v1.SearchRecordAPI/ListSearchRecord' },
  { title: '删除短信', description: '删除指定短信记录', method: 'GRPC', path: '/api.v1.SmsAPI/DeleteSms' },
  { title: '查看短信详情', description: '根据短信 ID 查看详情', method: 'GRPC', path: '/api.v1.SmsAPI/GetSms' },
  { title: '查看短信列表', description: '查看短信发送记录列表', method: 'GRPC', path: '/api.v1.SmsAPI/ListSms' },
  { title: '批量更新采集文章', description: '批量更新采集文章状态与内容（入采集/发布队列）', method: 'GRPC', path: '/api.v1.SpiderAPI/BatchUpdateSpiderArticleDetail' },
  { title: '批量更新采集文档', description: '批量更新采集文档字段与状态（入下载/发布队列）', method: 'GRPC', path: '/api.v1.SpiderAPI/BatchUpdateSpiderDocument' },
  { title: '创建文章嗅探来源', description: '新增文章列表页嗅探来源', method: 'GRPC', path: '/api.v1.SpiderAPI/CreateSpiderArticleList' },
  { title: '创建文档嗅探链接', description: '新增文档采集种子链接', method: 'GRPC', path: '/api.v1.SpiderAPI/CreateSpiderUrl' },
  { title: '删除采集文章', description: '删除指定采集文章', method: 'GRPC', path: '/api.v1.SpiderAPI/DeleteSpiderArticleDetail' },
  { title: '删除文章嗅探来源', description: '删除文章列表页嗅探来源', method: 'GRPC', path: '/api.v1.SpiderAPI/DeleteSpiderArticleList' },
  { title: '删除采集文档', description: '删除指定采集文档', method: 'GRPC', path: '/api.v1.SpiderAPI/DeleteSpiderDocument' },
  { title: '删除文档嗅探链接', description: '删除文档采集种子链接', method: 'GRPC', path: '/api.v1.SpiderAPI/DeleteSpiderUrl' },
  { title: '查看采集文章详情', description: '根据 ID 查看采集文章详情', method: 'GRPC', path: '/api.v1.SpiderAPI/GetSpiderArticleDetail' },
  { title: '查看文章嗅探来源详情', description: '根据 ID 查看文章列表页来源', method: 'GRPC', path: '/api.v1.SpiderAPI/GetSpiderArticleList' },
  { title: '查看采集文档详情', description: '根据 ID 查看采集文档详情', method: 'GRPC', path: '/api.v1.SpiderAPI/GetSpiderDocument' },
  { title: '查看文档嗅探链接详情', description: '根据 ID 查看文档采集链接', method: 'GRPC', path: '/api.v1.SpiderAPI/GetSpiderUrl' },
  { title: '查看采集文章列表', description: '查看采集文章记录列表', method: 'GRPC', path: '/api.v1.SpiderAPI/ListSpiderArticleDetail' },
  { title: '查看文章嗅探来源列表', description: '查看文章列表页来源列表', method: 'GRPC', path: '/api.v1.SpiderAPI/ListSpiderArticleList' },
  { title: '查看采集文档列表', description: '查看采集文档记录列表', method: 'GRPC', path: '/api.v1.SpiderAPI/ListSpiderDocument' },
  { title: '查看文档嗅探链接列表', description: '查看文档采集链接列表', method: 'GRPC', path: '/api.v1.SpiderAPI/ListSpiderUrl' },
  { title: '更新采集文章', description: '修改采集文章内容与状态', method: 'GRPC', path: '/api.v1.SpiderAPI/UpdateSpiderArticleDetail' },
  { title: '更新文章嗅探来源', description: '修改文章列表页嗅探来源', method: 'GRPC', path: '/api.v1.SpiderAPI/UpdateSpiderArticleList' },
  { title: '更新文章嗅探来源状态', description: '批量设置文章列表页嗅探状态', method: 'GRPC', path: '/api.v1.SpiderAPI/UpdateSpiderArticleListStatus' },
  { title: '更新采集文档', description: '修改采集文档字段与状态', method: 'GRPC', path: '/api.v1.SpiderAPI/UpdateSpiderDocument' },
  { title: '更新文档嗅探链接', description: '修改文档采集链接', method: 'GRPC', path: '/api.v1.SpiderAPI/UpdateSpiderUrl' },
  { title: '更新文档嗅探链接状态', description: '批量设置文档采集链接嗅探状态', method: 'GRPC', path: '/api.v1.SpiderAPI/UpdateSpiderUrlStatus' },
  { title: '创建用户', description: '新增系统用户', method: 'GRPC', path: '/api.v1.UserAPI/AddUser' },
  { title: '删除用户', description: '删除指定用户', method: 'GRPC', path: '/api.v1.UserAPI/DeleteUser' },
  { title: '查看用户详情', description: '根据用户 ID 查看详情', method: 'GRPC', path: '/api.v1.UserAPI/GetUser' },
  { title: '查看用户列表', description: '查看系统中的用户列表', method: 'GRPC', path: '/api.v1.UserAPI/ListUser' },
  { title: '设置用户密码与分组', description: '设置用户密码并调整所属分组', method: 'GRPC', path: '/api.v1.UserAPI/SetUser' },
  { title: '更新用户资料', description: '修改用户基础资料', method: 'GRPC', path: '/api.v1.UserAPI/UpdateUserProfile' },
  { title: '删除用户会员记录', description: '删除指定用户 VIP 记录', method: 'GRPC', path: '/api.v1.UserVipAPI/DeleteUserVip' },
  { title: '查看用户会员列表', description: '查看用户 VIP 会员记录列表', method: 'GRPC', path: '/api.v1.UserVipAPI/ListUserVip' },
  { title: '更新用户会员记录', description: '修改用户 VIP 权益与有效期', method: 'GRPC', path: '/api.v1.UserVipAPI/UpdateUserVip' },
  { title: '上传文章素材', description: '上传文章使用的图片、音频或视频', method: 'POST', path: '/api/v1/upload/article' },
  { title: '上传头像', description: '上传用户头像图片', method: 'POST', path: '/api/v1/upload/avatar' },
  { title: '上传轮播图素材', description: '上传轮播图图片文件', method: 'POST', path: '/api/v1/upload/banner' },
  { title: '上传分类封面', description: '上传文档分类封面图片', method: 'POST', path: '/api/v1/upload/category' },
  { title: '上传配置图片', description: '上传系统配置中使用的图片', method: 'POST', path: '/api/v1/upload/config' },
];

export interface ConfigSeed {
  category: string;
  name: string;
  label?: string;
  value: string;
  placeholder?: string;
  input_type: string;
  sort: number;
  options?: string;
  col_num?: number;
  is_secret?: boolean;
}

const closeStatement = `<div>尊敬的用户，您好：</div><div>为了给您带来更好的使用体验，<strong>山河图书馆</strong> 正在对服务进行升级维护，预计恢复时间为 <span style="color:red">2024-10-24 06:00:00</span>，请您稍后再进行访问。</div><div>升级维护期间，普通用户将无法正常使用（系统管理人员出于维护的需要不受升级影响）。</div><div>由此带来的不便，敬请谅解。</div>`;

interface OAuthSeedOptions {
  clientIdLabel?: string;
  clientIdPlaceholder?: string;
  extra?: Array<Omit<ConfigSeed, 'category'>>;
}

/** 生成一套标准第三方登录（OAuth）配置项 */
function oauthConfigSeed(
  category: string,
  title: string,
  devUrl: string,
  opts: OAuthSeedOptions = {},
): ConfigSeed[] {
  const type = category.replace(/^oauth/, '').toLowerCase();
  const seeds: ConfigSeed[] = [
    { category, name: 'enable', col_num: 8, label: '是否启用', value: 'false', placeholder: `启用后登录页显示「使用${title}登录」入口`, input_type: 'switch', sort: 10 },
    { category, name: 'client_id', col_num: 12, label: opts.clientIdLabel ?? 'Client ID', value: '', placeholder: opts.clientIdPlaceholder ?? `在${title}开放平台创建应用后获得`, input_type: 'text', sort: 20 },
    { category, name: 'client_secret', col_num: 12, label: 'Client Secret', value: '', input_type: 'text', sort: 30, is_secret: true },
    { category, name: 'redirect_url', col_num: 24, label: '授权回调地址', value: '', placeholder: `请将该地址填入${title}开放平台的授权回调域：/oauth/callback?type=${type}`, input_type: 'text', sort: 40 },
  ];
  if (devUrl) seeds.push({ category, name: 'dev_url', col_num: 24, label: '开放平台地址', value: devUrl, input_type: 'text', sort: 50 });
  for (const extra of opts.extra ?? []) seeds.push({ ...extra, category });
  return seeds;
}

export const CONFIG_SEED: ConfigSeed[] = [
  { category: 'system', name: 'sitename', col_num: 24, label: '网站名称', value: '山河图书馆', placeholder: '请输入您网站的名称，如：山河图书馆', input_type: 'text', sort: 10 },
  { category: 'system', name: 'domain', col_num: 24, label: '【重要】网站域名', value: 'https://lib.shanhe.co', placeholder: '请输入您网站的域名访问地址，带 https:// 或 http:// 如 https://lib.shanhe.co，用以生成网站地图sitemap', input_type: 'text', sort: 11 },
  { category: 'system', name: 'title', col_num: 24, label: '首页标题', value: '图书馆 - 山河大学', placeholder: '请输入您网站的首页标题，如：图书馆 - 山河大学', input_type: 'text', sort: 20 },
  { category: 'system', name: 'keywords', col_num: 24, label: '网站关键字', value: '图书馆 - 山河大学', placeholder: '请输入您网站的关键字', input_type: 'text', sort: 30 },
  { category: 'system', name: 'description', col_num: 24, label: '网站描述', value: '图书馆 - 山河大学', placeholder: '请输入您网站的描述', input_type: 'textarea', sort: 40 },
  { category: 'system', name: 'recommend_words', col_num: 24, label: '首页搜索推荐词', value: '', placeholder: '网站首页搜索推荐关键字，多个关键字用英文逗号分隔', input_type: 'text', sort: 50 },
  { category: 'system', name: 'logo', col_num: 12, label: '网站Logo', value: '', placeholder: '请上传一张图片作为网站Logo', input_type: 'image', sort: 60 },
  { category: 'system', name: 'favicon', col_num: 12, label: '网站Favicon', value: '', placeholder: '请上传一张方方正正的小图片作为网站favicon', input_type: 'image', sort: 61 },
  { category: 'system', name: 'register_background', col_num: 12, label: '注册页背景图', value: '', placeholder: '请上传一张图片作为注册页背景图', input_type: 'image', sort: 62 },
  { category: 'system', name: 'login_background', col_num: 12, label: '登录页背景图', value: '', placeholder: '请上传一张图片作为登录页背景图', input_type: 'image', sort: 63 },
  { category: 'system', name: 'sec_icp', col_num: 12, label: '公网安备', value: '', placeholder: '请输入您网站的公网安备备案号', input_type: 'text', sort: 68 },
  { category: 'system', name: 'icp', col_num: 12, label: '网站备案号', value: '', placeholder: '请输入您网站的备案号', input_type: 'text', sort: 69 },
  { category: 'system', name: 'copyright_start_year', col_num: 24, label: '版权起始年', value: '2019', placeholder: '请输入您网站版权起始年，如：2019', input_type: 'text', sort: 80 },
  { category: 'system', name: 'analytics', col_num: 24, label: '网站统计代码', value: '', placeholder: '请输入您网站的统计代码，当前只支持百度统计', input_type: 'textarea', sort: 90 },

  { category: 'captcha', name: 'height', label: '验证码高度', value: '60', placeholder: '请输入验证码高度，默认为60', input_type: 'number', sort: 13 },
  { category: 'captcha', name: 'width', label: '验证码宽度', value: '240', placeholder: '请输入验证码宽度，默认为240', input_type: 'number', sort: 14 },
  { category: 'captcha', name: 'length', label: '验证码长度', value: '5', placeholder: '请输入验证码长度，默认为6', input_type: 'number', sort: 15 },
  { category: 'captcha', name: 'type', label: '验证码类型', value: 'digit', placeholder: '请选择验证码类型，默认为数字', input_type: 'select', sort: 16, options: 'digit:数字\nalpha:字母\nstring:字母数字' },

  { category: 'security', name: 'max_document_size', col_num: 24, label: '最大文档大小(MB)', value: '50', placeholder: '允许用户上传的最大文档大小，默认为50，即50MB', input_type: 'number', sort: 1 },
  { category: 'security', name: 'comment_interval', col_num: 24, label: '评论时间间隔', value: '10', placeholder: '用户评论时间间隔，单位为秒。0表示不限制。', input_type: 'number', sort: 2 },
  { category: 'security', name: 'document_related_duration', col_num: 24, label: '文档的【相关文档】有效期', value: '7', placeholder: '文档的相关联文档的有效期，默认为7', input_type: 'number', sort: 15 },
  { category: 'security', name: 'attachment_retention_minute', col_num: 24, label: '从回收站清除的文档文件保留时长', value: '1440', placeholder: '单位为分钟，默认为1440，即24小时', input_type: 'number', sort: 16 },
  { category: 'security', name: 'search_record_retention_days', col_num: 12, label: '搜索记录保留天数', value: '7', placeholder: '单位为天，默认为7，即7天。0表示不记录用户搜索记录。', input_type: 'number', sort: 17 },
  { category: 'security', name: 'document_allowed_ext', col_num: 12, label: '允许上传的文档类型', value: '', placeholder: '留空表示允许程序所支持的全部文档类型', input_type: 'select-multi', sort: 17, options: '.doc\n.docx\n.rtf\n.wps\n.odt\n.dot\n.xls\n.xlsx\n.csv\n.tsv\n.ppt\n.pptx\n.pps\n.dps\n.odp\n.doc\n.docx\n.rtf' },
  { category: 'security', name: 'is_close', col_num: 8, label: '是否关闭网站', value: 'false', placeholder: '请选择是否关闭网站', input_type: 'switch', sort: 160 },
  { category: 'security', name: 'close_statement', col_num: 24, label: '闭站说明', value: closeStatement, placeholder: '关闭网站后，页面提示内容（支持HTML）', input_type: 'textarea', sort: 170 },
  { category: 'security', name: 'enable_register', col_num: 8, label: '是否允许注册', value: 'true', placeholder: '请选择是否允许用户注册', input_type: 'switch', sort: 18 },
  { category: 'security', name: 'login_required', col_num: 8, label: '是否登录才能访问', value: 'false', placeholder: '用户是否登录了才能访问', input_type: 'switch', sort: 18 },
  { category: 'security', name: 'enable_captcha_login', col_num: 8, label: '是否开启登录验证码', value: 'true', placeholder: '请选择是否开启登录验证码', input_type: 'switch', sort: 19 },
  { category: 'security', name: 'enable_captcha_register', col_num: 8, label: '是否开启注册验证码', value: 'true', placeholder: '请选择是否开启注册验证码', input_type: 'switch', sort: 20 },
  { category: 'security', name: 'enable_captcha_comment', col_num: 8, label: '是否开启评论验证码', value: 'true', placeholder: '请选择是否开启评论验证码', input_type: 'switch', sort: 21 },
  { category: 'security', name: 'enable_captcha_find_password', col_num: 8, label: '是否开启找回密码验证码', value: 'true', placeholder: '请选择是否开启找回密码验证码', input_type: 'switch', sort: 22 },
  { category: 'security', name: 'enable_verify_register_email', col_num: 8, label: '是否开启注册邮箱验证', value: 'false', placeholder: '用户注册时是否需要验证邮箱', input_type: 'switch', sort: 50 },

  { category: 'footer', name: 'about', label: '关于我们', value: '/article/about', placeholder: '请输入关于我们的链接地址，留空表示不显示', input_type: 'text', sort: 24 },
  { category: 'footer', name: 'contact', label: '联系我们', value: '/article/contact', placeholder: '请输入联系我们的链接地址，留空表示不显示', input_type: 'text', sort: 25 },
  { category: 'footer', name: 'agreement', label: '文库协议', value: '/article/agreement', placeholder: '请输入文库协议的链接地址，留空表示不显示', input_type: 'text', sort: 26 },
  { category: 'footer', name: 'copyright', label: '免责声明', value: '/article/copyright', placeholder: '请输入免责声明的链接地址，留空表示不显示', input_type: 'text', sort: 27 },
  { category: 'footer', name: 'feedback', label: '意见反馈', value: '/article/feedback', placeholder: '请输入意见反馈的链接地址，留空表示不显示', input_type: 'text', sort: 28 },

  { category: 'converter', name: 'max_preview_percent', col_num: 24, label: '最大预览页数百分比', value: '100', placeholder: '百分比数值，填1~100', input_type: 'number', sort: -1 },
  { category: 'converter', name: 'max_preview', col_num: 12, label: '最大预览页数', value: '12', placeholder: '文档允许的最大预览页数，0表示不限制', input_type: 'number', sort: 0 },
  { category: 'converter', name: 'timeout', col_num: 12, label: '转换超时(分钟)', value: '30', placeholder: '文档转换超时时间，默认为30分钟', input_type: 'number', sort: 20 },
  { category: 'converter', name: 'extension', col_num: 12, label: '预览格式', value: 'webp', placeholder: '将文档转为特定格式以供预览', input_type: 'select', sort: 30, options: 'svg:SVG\njpg:JPEG\npng:PNG\nwebp:WEBP' },
  { category: 'converter', name: 'enable_convert_repeated_document', col_num: 12, label: '是否转换重复文档', value: 'false', placeholder: '对于已转换过的文档，再次被上传时是否再转换一次', input_type: 'switch', sort: 31 },
  { category: 'converter', name: 'enable_gzip', col_num: 24, label: '是否启用GZIP压缩', value: 'true', placeholder: '是否对文档SVG预览文件启用GZIP压缩', input_type: 'switch', sort: 40 },
  { category: 'converter', name: 'enable_svgo', col_num: 24, label: '是否启用SVGO', value: 'false', placeholder: '是否对文档SVG预览文件启用SVGO压缩', input_type: 'switch', sort: 50 },

  { category: 'download', name: 'enable_guest_download', col_num: 12, label: '是否允许游客下载', value: 'false', placeholder: '启用之后，未登录用户可以下载免费文档', input_type: 'switch', sort: 10 },
  { category: 'download', name: 'free_download_duration', col_num: 12, label: '购买文档后多少天内允许免费重复下载', value: '0', placeholder: '0表示再次下载仍需购买', input_type: 'number', sort: 20 },
  { category: 'download', name: 'url_duration', col_num: 12, label: '下载链接有效时长(秒)', value: '60', placeholder: '生成文档下载链接后多少秒之后链接失效', input_type: 'number', sort: 30 },
  { category: 'download', name: 'times_every_day', col_num: 12, label: '允许登录用户每天下载次数', value: '10', placeholder: '允许登录用户每天下载次数，0表示不允许下载', input_type: 'number', sort: 40 },
  { category: 'download', name: 'times_every_ip', col_num: 12, label: '允许每个IP每天下载次数', value: '10', placeholder: '允许每个IP每天下载的次数', input_type: 'number', sort: 41 },
  { category: 'download', name: 'secret_key', col_num: 12, label: '链接签名密钥', value: 'moredoc', placeholder: '链接签名密钥，用于加密下载链接', input_type: 'text', sort: 50 },

  { category: 'score', name: 'credit_name', col_num: 8, label: '积分名称', value: '魔豆', placeholder: '请输入网站的积分名称，默认为魔豆', input_type: 'text', sort: 1 },
  { category: 'score', name: 'register', col_num: 8, label: '注册', value: '10', placeholder: '注册时获得的积分', input_type: 'number', sort: 10 },
  { category: 'score', name: 'sign_in', col_num: 8, label: '签到', value: '1', placeholder: '每日签到获得的积分', input_type: 'number', sort: 20 },
  { category: 'score', name: 'delete_document', col_num: 8, label: '删除文档', value: '1', placeholder: '删除上传文档扣除的积分，0表示不扣除', input_type: 'number', sort: 25 },
  { category: 'score', name: 'upload_document', col_num: 8, label: '上传文档', value: '5', placeholder: '上传一篇文档可获得的积分', input_type: 'number', sort: 30 },
  { category: 'score', name: 'upload_document_limit', col_num: 16, label: '每日上传文档奖励次数', value: '1', placeholder: '每天最多可以获得多少次文档上传奖励，0表示无奖励。', input_type: 'number', sort: 40 },
  { category: 'score', name: 'document_collected', col_num: 8, label: '文档被收藏', value: '1', placeholder: '上传的文档被收藏后获得的积分', input_type: 'number', sort: 50 },
  { category: 'score', name: 'document_collected_limit', col_num: 16, label: '每日文档被收藏奖励次数', value: '1', placeholder: '每天最多可以获得多少次文档被收藏奖励', input_type: 'number', sort: 60 },
  { category: 'score', name: 'document_commented', col_num: 8, label: '文档被评论', value: '1', placeholder: '上传的文档被评论后获得的积分', input_type: 'number', sort: 70 },
  { category: 'score', name: 'document_commented_limit', col_num: 16, label: '每日文档被评论奖励次数', value: '1', placeholder: '每天最多可以获得多少次文档被评论奖励', input_type: 'number', sort: 80 },

  { category: 'email', name: 'enable', label: '是否启用邮件服务', value: 'false', placeholder: '邮件服务，用于找回账户密码', input_type: 'switch', sort: 10 },
  { category: 'email', name: 'host', label: 'SMTP 服务器地址', value: '', placeholder: '如：smtp.exmail.com', input_type: 'text', sort: 20 },
  { category: 'email', name: 'port', label: 'SMTP 服务器端口', value: '465', placeholder: '如：465', input_type: 'number', sort: 30 },
  { category: 'email', name: 'is_tls', label: '是否启用TLS', value: 'true', placeholder: '如果是TLS端口，请启用', input_type: 'switch', sort: 40 },
  { category: 'email', name: 'from_name', label: '发件人名称', value: '', placeholder: '请输入您要展示的发件人名称', input_type: 'text', sort: 50 },
  { category: 'email', name: 'username', label: 'SMTP 账号', value: '', placeholder: '请输入您的邮箱账户', input_type: 'text', sort: 60 },
  { category: 'email', name: 'password', label: 'SMTP 密码', value: '', placeholder: '请输入您的邮箱密码', input_type: 'password', sort: 70, is_secret: true },
  { category: 'email', name: 'duration', label: '邮件有效期', value: '30', placeholder: '找回密码时链接有效期，默认为30，表示30分钟', input_type: 'number', sort: 80 },
  { category: 'email', name: 'secret', label: '签名密钥', value: 'moredoc', placeholder: '找回密码链接签名密钥', input_type: 'text', sort: 80 },
  { category: 'email', name: 'test_email', label: '测试邮箱', value: '', placeholder: '用于每次变更配置时保存发送测试邮件', input_type: 'text', sort: 90 },

  { category: 'display', name: 'show_document_count', col_num: 8, label: '是否显示文档数', value: 'true', placeholder: '是否显示网站文档数', input_type: 'switch', sort: 0 },
  { category: 'display', name: 'show_document_download_count', col_num: 8, label: '是否显示文档下载数', value: 'true', placeholder: '是否显示文档被下载次数', input_type: 'switch', sort: 1 },
  { category: 'display', name: 'show_document_view_count', col_num: 8, label: '是否显示文档浏览数', value: 'true', placeholder: '是否显示文档被浏览次数', input_type: 'switch', sort: 2 },
  { category: 'display', name: 'show_document_favorite_count', col_num: 8, label: '是否显示文档收藏数', value: 'true', placeholder: '是否显示文档被收藏次数', input_type: 'switch', sort: 3 },
  { category: 'display', name: 'show_register_user_count', col_num: 8, label: '是否显示注册用户数', value: 'true', placeholder: '网站首页，是否显示注册用户数', input_type: 'switch', sort: 10 },
  { category: 'display', name: 'virtual_register_count', col_num: 24, label: '网站虚拟注册用户数', value: '0', placeholder: '网站首页显示的用户数=真实注册用户数+虚拟注册用户数', input_type: 'number', sort: 20 },
  { category: 'display', name: 'show_document_descriptions', col_num: 8, label: '是否显示文档摘要', value: 'true', placeholder: '文档阅读页面，是否显示文档摘要等信息', input_type: 'switch', sort: 21 },
  { category: 'display', name: 'show_index_categories', col_num: 8, label: '是否显示横栏分类', value: 'true', placeholder: '网站首页中间横栏位置，是否显示分类', input_type: 'switch', sort: 30 },
  { category: 'display', name: 'index_document_style', col_num: 8, label: '首页文档展示方式', value: 'card', placeholder: '默认为卡片方式', input_type: 'select', sort: 31, options: 'card:卡片\nlist:列表' },
  { category: 'display', name: 'home_version', col_num: 8, label: '首页版本', value: 'v1', placeholder: '默认为V1版，即旧版本', input_type: 'select', sort: 31, options: 'v1:V1版\nv2:V2版' },
  { category: 'display', name: 'pages_per_read', col_num: 8, label: '文档【继续阅读】的页数', value: '5', placeholder: '用户阅读文档，每次点击继续阅读按钮时阅读的页数，默认为5，表示5页', input_type: 'number', sort: 40 },
  { category: 'display', name: 'max_search_pages', col_num: 8, label: '文档搜索结果最大页数', value: '100', placeholder: '搜索结果，默认最大展示100页，0表示不限制', input_type: 'number', sort: 50 },
  { category: 'display', name: 'copyright_statement', col_num: 24, label: '版权声明', value: '本站文档数据由用户上传，仅供学习交流，如侵犯您的权益，请联系我们进行删除。', placeholder: '网站最底部版权声明，支持HTML', input_type: 'textarea', sort: 60 },
  { category: 'display', name: 'hide_keywords_on_lists', col_num: 8, label: '隐藏关键字', value: 'false', placeholder: '文档列表页，是否隐藏右侧关键字', input_type: 'switch', sort: 70 },
  { category: 'display', name: 'hide_category_without_document', col_num: 16, label: '隐藏无文档分类', value: 'false', placeholder: '对于分类下没有文档的分类，是否在前台页面进行隐藏', input_type: 'switch', sort: 80 },
  { category: 'display', name: 'wechat_tip', col_num: 24, label: '微信/微信公众号提示文案', value: '我们的公众号同样精彩', placeholder: '全局右下角【固定栏】微信/微信公众号提示文案', input_type: 'text', sort: 100 },
  { category: 'display', name: 'wechat_qrcode', col_num: 24, label: '微信/微信公众号二维码', value: '', placeholder: '全局右下角【固定栏】微信/微信公众号二维码图片。不存在则不显示', input_type: 'image', sort: 110 },
  { category: 'display', name: 'contact_tip', col_num: 24, label: '联系我们提示文案', value: '联系我们，反馈您的意见与建议', placeholder: '全局右下角【固定栏】联系我们的提示文案', input_type: 'text', sort: 120 },
  { category: 'display', name: 'contact_link', col_num: 24, label: '联系我们跳转链接', value: '', placeholder: '全局右下角【固定栏】联系我们链接地址。不存在则不显示', input_type: 'text', sort: 130 },

  { category: 'release', name: 'source', label: '版本检测来源', value: 'auto', input_type: 'select', sort: 10, options: 'none:不检测\nauto:自动检测\ngitee:Gitee\ngithub:GitHub' },
  { category: 'release', name: 'tag_name', label: '最新版版本号', value: '', input_type: 'text', sort: 20 },
  { category: 'release', name: 'name', label: '版本发布名称', value: '', input_type: 'text', sort: 30 },
  { category: 'release', name: 'body', label: '版本发布说明', value: '', input_type: 'textarea', sort: 40 },
  { category: 'release', name: 'ignore', label: '忽略版本提示', value: '', input_type: 'text', sort: 50 },

  // 存储：阿里云 OSS。启用后通用附件（图片/头像/文章资源）上传到 OSS，文档原文件仍存本地用于预览转换
  { category: 'storage', name: 'enable_oss', col_num: 8, label: '是否启用 OSS', value: 'false', placeholder: '启用后图片/头像等附件将上传到阿里云 OSS', input_type: 'switch', sort: 10 },
  { category: 'storage', name: 'oss_region', col_num: 8, label: 'OSS 区域', value: '', placeholder: '如 oss-cn-hangzhou', input_type: 'text', sort: 20 },
  { category: 'storage', name: 'oss_bucket', col_num: 8, label: 'Bucket 名称', value: '', placeholder: 'OSS 存储桶名称', input_type: 'text', sort: 30 },
  { category: 'storage', name: 'oss_access_key_id', col_num: 12, label: 'AccessKey ID', value: '', placeholder: '阿里云 AccessKey ID', input_type: 'text', sort: 40, is_secret: true },
  { category: 'storage', name: 'oss_access_key_secret', col_num: 12, label: 'AccessKey Secret', value: '', placeholder: '阿里云 AccessKey Secret', input_type: 'text', sort: 41, is_secret: true },
  { category: 'storage', name: 'oss_domain', col_num: 16, label: '自定义访问域名', value: '', placeholder: '可选，绑定到 OSS 的 CDN/自定义域名，留空则用 {bucket}.{region}.aliyuncs.com', input_type: 'text', sort: 50 },

  // ===== 专业版配置（对应 moredoc-web-pro 后台） =====
  // 系统：短信登录入口开关
  { category: 'system', name: 'enable_sms', col_num: 8, label: '是否启用短信服务', value: 'false', placeholder: '启用后，登录/注册/找回密码页显示手机短信验证入口', input_type: 'switch', sort: 100 },
  // 安全：小程序扫码登录、待支付订单超时
  { category: 'security', name: 'enable_wechatmp_pc_login', col_num: 12, label: 'PC端微信小程序扫码登录', value: 'false', placeholder: '启用后 PC 登录页显示微信小程序扫码登录入口', input_type: 'switch', sort: 60 },
  { category: 'security', name: 'order_close_minutes', col_num: 12, label: '待支付订单超时关闭(分钟)', value: '30', placeholder: '待支付订单超过该时长自动关闭，默认30分钟', input_type: 'number', sort: 61 },
  // 积分：人民币兑积分比率
  { category: 'score', name: 'credit_exchange', col_num: 8, label: '人民币兑积分比率', value: '10', placeholder: '1元人民币可兑换的积分数量，如10表示1元=10积分', input_type: 'number', sort: 90 },

  // VIP 会员
  { category: 'vip', name: 'enable', col_num: 8, label: '是否启用VIP', value: 'false', input_type: 'switch', sort: 10 },
  { category: 'vip', name: 'icon', col_num: 8, label: 'VIP图标', value: '', placeholder: '用户头像上的VIP标识图标', input_type: 'image', sort: 20 },
  { category: 'vip', name: 'enable_credit_pay', col_num: 8, label: '是否允许积分购买VIP', value: 'false', input_type: 'switch', sort: 30 },
  { category: 'vip', name: 'year_price', col_num: 8, label: '年卡价格(分)', value: '0', placeholder: '单位：分，如19900表示199元', input_type: 'number', sort: 100 },
  { category: 'vip', name: 'year_original_price', col_num: 8, label: '年卡原价(分)', value: '0', input_type: 'number', sort: 101 },
  { category: 'vip', name: 'year_document_discount', col_num: 8, label: '年卡文档折扣(十分之一折)', value: '100', placeholder: '如90表示9折，100表示不打折', input_type: 'number', sort: 102 },
  { category: 'vip', name: 'year_download', col_num: 8, label: '年卡专享下载次数', value: '0', placeholder: '年卡周期内VIP文档免费下载总次数，0表示不限', input_type: 'number', sort: 103 },
  { category: 'vip', name: 'year_times_every_day', col_num: 8, label: '年卡每日下载次数', value: '0', placeholder: '0表示不限', input_type: 'number', sort: 104 },
  { category: 'vip', name: 'quarter_price', col_num: 8, label: '季卡价格(分)', value: '0', input_type: 'number', sort: 200 },
  { category: 'vip', name: 'quarter_original_price', col_num: 8, label: '季卡原价(分)', value: '0', input_type: 'number', sort: 201 },
  { category: 'vip', name: 'quarter_document_discount', col_num: 8, label: '季卡文档折扣', value: '100', input_type: 'number', sort: 202 },
  { category: 'vip', name: 'quarter_download', col_num: 8, label: '季卡专享下载次数', value: '0', input_type: 'number', sort: 203 },
  { category: 'vip', name: 'quarter_times_every_day', col_num: 8, label: '季卡每日下载次数', value: '0', input_type: 'number', sort: 204 },
  { category: 'vip', name: 'month_price', col_num: 8, label: '月卡价格(分)', value: '0', input_type: 'number', sort: 300 },
  { category: 'vip', name: 'month_original_price', col_num: 8, label: '月卡原价(分)', value: '0', input_type: 'number', sort: 301 },
  { category: 'vip', name: 'month_document_discount', col_num: 8, label: '月卡文档折扣', value: '100', input_type: 'number', sort: 302 },
  { category: 'vip', name: 'month_download', col_num: 8, label: '月卡专享下载次数', value: '0', input_type: 'number', sort: 303 },
  { category: 'vip', name: 'month_times_every_day', col_num: 8, label: '月卡每日下载次数', value: '0', input_type: 'number', sort: 304 },

  // 微信小程序
  { category: 'mp', name: 'enable', col_num: 8, label: '是否启用小程序', value: 'false', input_type: 'switch', sort: 10 },
  { category: 'mp', name: 'appid', col_num: 12, label: '小程序AppID', value: '', input_type: 'text', sort: 20 },
  { category: 'mp', name: 'appsecret', col_num: 12, label: '小程序AppSecret', value: '', input_type: 'text', sort: 30, is_secret: true },
  { category: 'mp', name: 'token', col_num: 12, label: '消息校验Token', value: '', input_type: 'text', sort: 40 },
  { category: 'mp', name: 'encoding_aes_key', col_num: 12, label: '消息加解密密钥', value: '', input_type: 'text', sort: 50, is_secret: true },

  // 全文搜索
  { category: 'fulltext_search', name: 'enable', col_num: 8, label: '是否启用全文搜索', value: 'false', input_type: 'switch', sort: 10 },
  { category: 'fulltext_search', name: 'engine', col_num: 8, label: '搜索引擎', value: 'mysql', input_type: 'select', sort: 20, options: 'mysql:MySQL FULLTEXT\nelasticsearch:Elasticsearch\nmeilisearch:MeiliSearch' },
  { category: 'fulltext_search', name: 'host', col_num: 8, label: '搜索引擎地址', value: '127.0.0.1', placeholder: '如 127.0.0.1', input_type: 'text', sort: 30 },
  { category: 'fulltext_search', name: 'port', col_num: 8, label: '端口', value: '9200', input_type: 'number', sort: 40 },
  { category: 'fulltext_search', name: 'index', col_num: 8, label: '索引名', value: 'moredoc', input_type: 'text', sort: 50 },
  { category: 'fulltext_search', name: 'password', col_num: 8, label: '密码', value: '', input_type: 'text', sort: 60, is_secret: true },
  { category: 'fulltext_search', name: 'api_key', col_num: 24, label: 'API Key', value: '', placeholder: 'MeiliSearch 等使用 API Key 的引擎填写', input_type: 'text', sort: 80, is_secret: true },

  // 采集
  { category: 'spider', name: 'enable', col_num: 8, label: '是否启用自动采集', value: 'false', placeholder: '关闭后采集任务不再被后台自动调度，仍可手动入队', input_type: 'switch', sort: 10 },
  { category: 'spider', name: 'concurrency', col_num: 8, label: '并发任务数', value: '3', input_type: 'number', sort: 20 },
  { category: 'spider', name: 'timeout', col_num: 8, label: '请求超时(秒)', value: '15', input_type: 'number', sort: 30 },
  { category: 'spider', name: 'interval', col_num: 8, label: '调度间隔(分钟)', value: '5', placeholder: '后台每隔多少分钟扫描一次待采集队列', input_type: 'number', sort: 40 },
  { category: 'spider', name: 'user_agent', col_num: 24, label: 'User-Agent', value: 'Mozilla/5.0 (compatible; moredoc-spider)', input_type: 'text', sort: 50 },
  { category: 'spider', name: 'proxy', col_num: 24, label: '代理地址', value: '', placeholder: '如 http://127.0.0.1:7890，留空不使用代理', input_type: 'text', sort: 60 },
  { category: 'spider', name: 'render_service', col_num: 24, label: '浏览器渲染服务地址', value: '', placeholder: 'enable_browser=true 的任务使用该渲染服务（返回渲染后HTML），留空则退化为普通请求', input_type: 'text', sort: 70 },

  // 微信支付
  { category: 'wechatpay', name: 'enable_wechatpay', col_num: 8, label: '是否启用微信支付', value: 'false', input_type: 'switch', sort: 10 },
  { category: 'wechatpay', name: 'appid', col_num: 12, label: 'AppID', value: '', placeholder: '公众号/小程序/移动应用 AppID', input_type: 'text', sort: 20 },
  { category: 'wechatpay', name: 'mchid', col_num: 12, label: '微信支付商户号', value: '', input_type: 'text', sort: 30 },
  { category: 'wechatpay', name: 'serial_no', col_num: 12, label: '商户证书序列号', value: '', input_type: 'text', sort: 40 },
  { category: 'wechatpay', name: 'api_v3_key', col_num: 12, label: 'APIv3密钥', value: '', input_type: 'text', sort: 50, is_secret: true },
  { category: 'wechatpay', name: 'private_key', col_num: 24, label: '商户API私钥(apiclient_key.pem)', value: '', placeholder: '粘贴 apiclient_key.pem 全部内容（含 BEGIN/END）', input_type: 'textarea', sort: 60, is_secret: true },
  { category: 'wechatpay', name: 'public_key_id', col_num: 12, label: '微信支付公钥ID', value: '', input_type: 'text', sort: 70 },
  { category: 'wechatpay', name: 'public_key', col_num: 24, label: '微信支付公钥', value: '', placeholder: '微信支付公钥与平台证书二选一填写', input_type: 'textarea', sort: 80, is_secret: true },
  { category: 'wechatpay', name: 'platform_cert', col_num: 24, label: '微信支付平台证书', value: '', placeholder: '可点击【获取平台证书】自动获取，与微信支付公钥二选一', input_type: 'textarea', sort: 90, is_secret: true },
  { category: 'wechatpay', name: 'enable_sandbox', col_num: 8, label: '是否启用沙箱环境', value: 'false', input_type: 'switch', sort: 100 },

  // 支付宝
  { category: 'alipay', name: 'enable_alipay', col_num: 8, label: '是否启用支付宝支付', value: 'false', input_type: 'switch', sort: 10 },
  { category: 'alipay', name: 'appid', col_num: 12, label: '支付宝AppID', value: '', input_type: 'text', sort: 20 },
  { category: 'alipay', name: 'gateway', col_num: 12, label: '网关环境', value: 'https://openapi.alipay.com/gateway.do', input_type: 'select', sort: 30, options: 'https://openapi.alipay.com/gateway.do:正式环境\nhttps://openapi-sandbox.dl.alipaydev.com/gateway.do:沙箱环境' },
  { category: 'alipay', name: 'private_key', col_num: 24, label: '应用私钥', value: '', input_type: 'textarea', sort: 40, is_secret: true },
  { category: 'alipay', name: 'public_key', col_num: 24, label: '支付宝公钥', value: '', input_type: 'textarea', sort: 50, is_secret: true },

  // 虎皮椒
  { category: 'xunhupay', name: 'enable_xunhupay', col_num: 8, label: '是否启用虎皮椒支付', value: 'false', input_type: 'switch', sort: 10 },
  { category: 'xunhupay', name: 'xunhupay_name', col_num: 8, label: '支付方式显示名称', value: '虎皮椒支付', input_type: 'text', sort: 20 },
  { category: 'xunhupay', name: 'appid', col_num: 12, label: 'AppID', value: '', input_type: 'text', sort: 30 },
  { category: 'xunhupay', name: 'app_secret', col_num: 12, label: 'AppSecret', value: '', input_type: 'text', sort: 40, is_secret: true },
  { category: 'xunhupay', name: 'gateway_url', col_num: 12, label: '网关地址', value: 'https://api.xunhupay.com', input_type: 'text', sort: 50 },

  // 短信
  { category: 'sms', name: 'sms_provider', col_num: 24, label: '短信服务商', value: 'smsAliyun', placeholder: '切换服务商后，请在右侧填写对应服务商配置并分别保存', input_type: 'select', sort: 10, options: 'smsAliyun:阿里云\nsmsTencent:腾讯云\nsmsBaidu:百度云\nsmsHuawei:华为云\nsmsHaomas:浩信' },

  { category: 'smsAliyun', name: 'enable', col_num: 8, label: '是否启用', value: 'false', input_type: 'switch', sort: 10 },
  { category: 'smsAliyun', name: 'access_key_id', col_num: 12, label: 'AccessKey ID', value: '', input_type: 'text', sort: 20 },
  { category: 'smsAliyun', name: 'access_key_secret', col_num: 12, label: 'AccessKey Secret', value: '', input_type: 'text', sort: 30, is_secret: true },
  { category: 'smsAliyun', name: 'sign_name', col_num: 12, label: '短信签名', value: '', input_type: 'text', sort: 40 },
  { category: 'smsAliyun', name: 'template_code', col_num: 12, label: '验证码模板CODE', value: '', placeholder: '模板变量须为 ${code}', input_type: 'text', sort: 50 },

  { category: 'smsTencent', name: 'enable', col_num: 8, label: '是否启用', value: 'false', input_type: 'switch', sort: 10 },
  { category: 'smsTencent', name: 'secret_id', col_num: 12, label: 'SecretId', value: '', input_type: 'text', sort: 20 },
  { category: 'smsTencent', name: 'secret_key', col_num: 12, label: 'SecretKey', value: '', input_type: 'text', sort: 30, is_secret: true },
  { category: 'smsTencent', name: 'app_id', col_num: 12, label: 'SdkAppId', value: '', input_type: 'text', sort: 40 },
  { category: 'smsTencent', name: 'sign_name', col_num: 12, label: '短信签名', value: '', input_type: 'text', sort: 50 },
  { category: 'smsTencent', name: 'template_id', col_num: 12, label: '验证码模板ID', value: '', input_type: 'text', sort: 60 },

  { category: 'smsBaidu', name: 'enable', col_num: 8, label: '是否启用', value: 'false', input_type: 'switch', sort: 10 },
  { category: 'smsBaidu', name: 'access_key', col_num: 12, label: 'Access Key', value: '', input_type: 'text', sort: 20 },
  { category: 'smsBaidu', name: 'secret_key', col_num: 12, label: 'Secret Key', value: '', input_type: 'text', sort: 30, is_secret: true },
  { category: 'smsBaidu', name: 'sign_name', col_num: 12, label: '短信签名', value: '', input_type: 'text', sort: 40 },
  { category: 'smsBaidu', name: 'template_id', col_num: 12, label: '验证码模板ID', value: '', input_type: 'text', sort: 50 },

  { category: 'smsHuawei', name: 'enable', col_num: 8, label: '是否启用', value: 'false', input_type: 'switch', sort: 10 },
  { category: 'smsHuawei', name: 'app_key', col_num: 12, label: 'App Key', value: '', input_type: 'text', sort: 20 },
  { category: 'smsHuawei', name: 'app_secret', col_num: 12, label: 'App Secret', value: '', input_type: 'text', sort: 30, is_secret: true },
  { category: 'smsHuawei', name: 'sender', col_num: 12, label: '签名通道号', value: '', input_type: 'text', sort: 40 },
  { category: 'smsHuawei', name: 'template_id', col_num: 12, label: '验证码模板ID', value: '', input_type: 'text', sort: 50 },

  { category: 'smsHaomas', name: 'enable', col_num: 8, label: '是否启用', value: 'false', input_type: 'switch', sort: 10 },
  { category: 'smsHaomas', name: 'api_url', col_num: 12, label: '接口地址', value: 'https://api.haomas.com/sms/v1', input_type: 'text', sort: 20 },
  { category: 'smsHaomas', name: 'app_id', col_num: 12, label: 'AppID', value: '', input_type: 'text', sort: 30 },
  { category: 'smsHaomas', name: 'app_key', col_num: 12, label: 'AppKey', value: '', input_type: 'text', sort: 40, is_secret: true },
  { category: 'smsHaomas', name: 'template_code', col_num: 12, label: '验证码模板编号', value: '', input_type: 'text', sort: 50 },

  // 第三方登录 OAuth（自定义 SSO 接入 user-center）
  ...oauthConfigSeed('oauthCustom', '自定义Oauth', '', {
    clientIdLabel: 'Client ID',
    clientIdPlaceholder: '由统一身份中心(user-center)分配的 client_id（SSO 接入方默认 shanhe_lib_client）',
    extra: [
      { name: 'authorize_url', label: '授权地址', value: '', placeholder: '如 https://example.com/oauth/authorize', input_type: 'text', sort: 90 },
      { name: 'token_url', label: '获取Token地址', value: '', input_type: 'text', sort: 100 },
      { name: 'userinfo_url', label: '获取用户信息地址', value: '', input_type: 'text', sort: 110 },
      { name: 'scope', label: '授权范围(scope)', value: '', input_type: 'text', sort: 120 },
      { name: 'issuer', label: 'OIDC Issuer', value: '', placeholder: '须与统一身份中心 discovery 的 issuer 完全一致，如 https://apiuser.shanhe.co/api', input_type: 'text', sort: 130 },
    ],
  }),
];

export const GROUPS_SEED = [
  { id: 1, title: '超级管理员', is_display: true, description: '系统超级管理员', user_count: 0, sort: 0, enable_upload: true, enable_document_review: false, enable_comment: true, enable_comment_approval: false },
  { id: 2, title: '普通用户', is_display: true, description: '普通用户', user_count: 0, sort: 0, is_default: true, enable_upload: false, enable_document_review: true, enable_comment: true, enable_comment_approval: true },
];

export const FRIENDLINKS_SEED = [
  { title: '摩枫网络科技', link: 'https://mnt.ltd', enable: true },
  { title: '书栈网', link: 'https://www.bookstack.cn', enable: true },
];

export const ARTICLES_SEED = [
  { identifier: 'about', title: '关于我们', content: '请输入【关于我们】的内容', user_id: 1, status: 1 },
  { identifier: 'agreement', title: '文库协议', content: '请输入【文库协议】的内容', user_id: 1, status: 1 },
  { identifier: 'contact', title: '联系我们', content: '请输入【联系我们】的内容', user_id: 1, status: 1 },
  { identifier: 'feedback', title: '意见反馈', content: '请输入【意见反馈】的内容', user_id: 1, status: 1 },
  { identifier: 'copyright', title: '免责声明', content: '请输入【免责声明】的内容', user_id: 1, status: 1 },
  { identifier: 'help', title: '使用帮助', content: '请输入【使用帮助】的内容', user_id: 1, status: 1 },
];

export const NAVIGATIONS_SEED = [
  { title: '首页', href: '/', target: '_self', color: '', sort: 102400, enable: true, fixed: true },
  { title: '文库资料', href: '/category', target: '_self', sort: 102300, enable: true, fixed: true },
  { title: '文章资讯', href: '/article', target: '_self', sort: 102200, enable: true, fixed: true },
];

export const LANGUAGES_SEED = [
  { language: '中文（简体）', code: 'zh-CN', enable: true },
  { language: '中文（繁体）', code: 'zh-TW', enable: true },
  { language: '英语', code: 'en', enable: true },
  { language: '法语', code: 'fr', enable: true },
  { language: '韩语', code: 'ko', enable: true },
  { language: '德语', code: 'de', enable: true },
  { language: '日语', code: 'ja', enable: true },
  { language: '俄语', code: 'ru', enable: true },
  { language: '阿尔巴尼亚语', code: 'sq', enable: false },
  { language: '南非荷兰语', code: 'af', enable: false },
  { language: '阿姆哈拉语', code: 'am', enable: false },
  { language: '阿拉伯语', code: 'ar', enable: false },
  { language: '亚美尼亚文', code: 'hy', enable: false },
  { language: '阿萨姆语', code: 'as', enable: false },
  { language: '艾马拉语', code: 'ay', enable: false },
  { language: '阿塞拜疆语', code: 'az', enable: false },
  { language: '班巴拉语', code: 'bm', enable: false },
  { language: '巴斯克语', code: 'eu', enable: false },
  { language: '白俄罗斯语', code: 'be', enable: false },
  { language: '孟加拉文', code: 'bn', enable: false },
  { language: '博杰普尔语', code: 'bho', enable: false },
  { language: '波斯尼亚语', code: 'bs', enable: false },
  { language: '保加利亚语', code: 'bg', enable: false },
  { language: '加泰罗尼亚语', code: 'ca', enable: false },
  { language: '宿务语', code: 'ceb', enable: false },
  { language: '科西嘉语', code: 'co', enable: false },
  { language: '克罗地亚语', code: 'hr', enable: false },
  { language: '捷克语', code: 'cs', enable: false },
  { language: '丹麦语', code: 'da', enable: false },
  { language: '迪维希语', code: 'dv', enable: false },
  { language: '多格来语', code: 'doi', enable: false },
  { language: '荷兰语', code: 'nl', enable: false },
  { language: '世界语', code: 'eo', enable: false },
  { language: '爱沙尼亚语', code: 'et', enable: false },
  { language: '埃维语', code: 'ee', enable: false },
  { language: '菲律宾语（塔加拉语）', code: 'fil', enable: false },
  { language: '芬兰语', code: 'fi', enable: false },
  { language: '弗里斯兰语', code: 'fy', enable: false },
  { language: '加利西亚语', code: 'gl', enable: false },
  { language: '格鲁吉亚语', code: 'ka', enable: false },
  { language: '希腊文', code: 'el', enable: false },
  { language: '瓜拉尼人', code: 'gn', enable: false },
  { language: '古吉拉特文', code: 'gu', enable: false },
  { language: '海地克里奥尔语', code: 'ht', enable: false },
  { language: '豪萨语', code: 'ha', enable: false },
  { language: '夏威夷语', code: 'haw', enable: false },
  { language: '希伯来语', code: 'he', enable: false },
  { language: '印地语', code: 'hi', enable: false },
  { language: '苗语', code: 'hmn', enable: false },
  { language: '匈牙利语', code: 'hu', enable: false },
  { language: '冰岛语', code: 'is', enable: false },
  { language: '伊博语', code: 'ig', enable: false },
  { language: '伊洛卡诺语', code: 'ilo', enable: false },
  { language: '印度尼西亚语', code: 'id', enable: false },
  { language: '爱尔兰语', code: 'ga', enable: false },
  { language: '意大利语', code: 'it', enable: false },
  { language: '爪哇语', code: 'jv', enable: false },
  { language: '卡纳达文', code: 'kn', enable: false },
  { language: '哈萨克语', code: 'kk', enable: false },
  { language: '高棉语', code: 'km', enable: false },
  { language: '卢旺达语', code: 'rw', enable: false },
  { language: '贡根语', code: 'gom', enable: false },
  { language: '克里奥尔语', code: 'kri', enable: false },
  { language: '库尔德语', code: 'ku', enable: false },
  { language: '库尔德语（索拉尼）', code: 'ckb', enable: false },
  { language: '吉尔吉斯语', code: 'ky', enable: false },
  { language: '老挝语', code: 'lo', enable: false },
  { language: '拉丁文', code: 'la', enable: false },
  { language: '拉脱维亚语', code: 'lv', enable: false },
  { language: '林格拉语', code: 'ln', enable: false },
  { language: '立陶宛语', code: 'lt', enable: false },
  { language: '卢干达语', code: 'lg', enable: false },
  { language: '卢森堡语', code: 'lb', enable: false },
  { language: '马其顿语', code: 'mk', enable: false },
  { language: '迈蒂利语', code: 'mai', enable: false },
  { language: '马尔加什语', code: 'mg', enable: false },
  { language: '马来语', code: 'ms', enable: false },
  { language: '马拉雅拉姆文', code: 'ml', enable: false },
  { language: '马耳他语', code: 'mt', enable: false },
  { language: '毛利语', code: 'mi', enable: false },
  { language: '马拉地语', code: 'mr', enable: false },
  { language: '梅泰语（曼尼普尔语）', code: 'mni-Mtei', enable: false },
  { language: '米佐语', code: 'lus', enable: false },
  { language: '蒙古文', code: 'mn', enable: false },
  { language: '缅甸语', code: 'my', enable: false },
  { language: '尼泊尔语', code: 'ne', enable: false },
  { language: '挪威语', code: 'no', enable: false },
  { language: '尼杨扎语（齐切瓦语）', code: 'ny', enable: false },
  { language: '奥里亚语（奥里亚）', code: 'or', enable: false },
  { language: '奥罗莫语', code: 'om', enable: false },
  { language: '普什图语', code: 'ps', enable: false },
  { language: '波斯语', code: 'fa', enable: false },
  { language: '波兰语', code: 'pl', enable: false },
  { language: '葡萄牙语（葡萄牙、巴西）', code: 'pt', enable: false },
  { language: '旁遮普语', code: 'pa', enable: false },
  { language: '克丘亚语', code: 'qu', enable: false },
  { language: '罗马尼亚语', code: 'ro', enable: false },
  { language: '萨摩亚语', code: 'sm', enable: false },
  { language: '梵语', code: 'sa', enable: false },
  { language: '苏格兰盖尔语', code: 'gd', enable: false },
  { language: '塞佩蒂语', code: 'nso', enable: false },
  { language: '塞尔维亚语', code: 'sr', enable: false },
  { language: '塞索托语', code: 'st', enable: false },
  { language: '修纳语', code: 'sn', enable: false },
  { language: '信德语', code: 'sd', enable: false },
  { language: '僧伽罗语', code: 'si', enable: false },
  { language: '斯洛伐克语', code: 'sk', enable: false },
  { language: '斯洛文尼亚语', code: 'sl', enable: false },
  { language: '索马里语', code: 'so', enable: false },
  { language: '西班牙语', code: 'es', enable: false },
  { language: '巽他语', code: 'su', enable: false },
  { language: '斯瓦希里语', code: 'sw', enable: false },
  { language: '瑞典语', code: 'sv', enable: false },
  { language: '塔加路语（菲律宾语）', code: 'tl', enable: false },
  { language: '塔吉克语', code: 'tg', enable: false },
  { language: '泰米尔语', code: 'ta', enable: false },
  { language: '鞑靼语', code: 'tt', enable: false },
  { language: '泰卢固语', code: 'te', enable: false },
  { language: '泰语', code: 'th', enable: false },
  { language: '蒂格尼亚语', code: 'ti', enable: false },
  { language: '宗加语', code: 'ts', enable: false },
  { language: '土耳其语', code: 'tr', enable: false },
  { language: '土库曼语', code: 'tk', enable: false },
  { language: '契维语（阿坎语）', code: 'ak', enable: false },
  { language: '乌克兰语', code: 'uk', enable: false },
  { language: '乌尔都语', code: 'ur', enable: false },
  { language: '维吾尔语', code: 'ug', enable: false },
  { language: '乌兹别克语', code: 'uz', enable: false },
  { language: '越南语', code: 'vi', enable: false },
  { language: '威尔士语', code: 'cy', enable: false },
  { language: '班图语', code: 'xh', enable: false },
  { language: '意第绪语', code: 'yi', enable: false },
  { language: '约鲁巴语', code: 'yo', enable: false },
  { language: '祖鲁语', code: 'zu', enable: false },
];